dist: xenial
language: minimal
sudo: false

services:
  - docker

matrix:
  include:
    - name: Airflow 1.10.4
      env:
        - AIRFLOW_VERSION=1.10.4
    - name: Airflow 1.10.4 with RBAC
      env:
        - AIRFLOW_VERSION=1.10.4
        - AIRFLOW__WEBSERVER__RBAC=true

script:
  - docker-compose -f docker-compose.yml build --build-arg "AIRFLOW_VERSION=${AIRFLOW_VERSION}"
  # Start the tests container (sut) and attach airflow stdout as well
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from=sut sut airflow

# deploy:
#   provider: pypi
#   user: epoch8
#   password: # TODO: Add epoch8's PyPI password. See https://docs.travis-ci.com/user/deployment/pypi
#   distributions: sdist bdist_wheel
#   on:
#     tags: true
